### ISSUE TITLE
Unquoted strings are parsed as identifiers

### ISSUE THREAD

**Issue by ozkutuk** [moleike/haskell-jsonnet#45]
Both identifiers and unquoted strings are pretty-printed the same way, but identifier parsing has higher priority than string parsing during parsing stage, causing the following behavior:
```haskell
ghci> import Language.Jsonnet.Syntax
ghci> import Language.Jsonnet.Common
ghci> import Language.Jsonnet.Pretty
ghci> import Language.Jsonnet.Test.Roundtrip
ghci> import qualified Data.Text as T
ghci> e = EStr "foo" Unquoted
ghci> parseExpr . T.pack . show . ppExpr $ e
Right (Fix (InL (EIdent "foo")))
```
This causes roundtrip tests to sometimes fail, since a pretty-printed unquoted string is later parsed as an identifier. Here is a hedgehog seed to see an example failing roundtrip test:
```bash
cabal run jsonnet-test -- -p "roundtrip" --hedgehog-replay "Size 91 Seed 12461984714529812419 8668381392682229415"
```

**Comment by moleike** [comment]
One problem here is that unquoted strings are only valid on field names, so it shouldn't be possible to construct it the way it's done with the current AST.

**Comment by moleike** [comment]
I think this could be solved by parsing unquoted strings (which only appear in fields) as identifiers and desugar them into strings and removing the `Unquoted` constructor.

**Comment by ozkutuk** [comment]
Do you think this should be fixed by modifiying the Hedgehog generators so that these kinds of values couldn't be generated anymore, or by modifying the AST such that it would be impossible to represent such a case?

**Comment by ozkutuk** [comment]
> I think this could be solved by parsing unquoted strings (which only appear in fields) as identifiers and desugar them into strings and removing the `Unquoted` constructor.

I missed this comment on my previous message. I am not familiar enough with the AST to have an opinion this, but I'll take a look.

**Comment by moleike** [comment]
Let me try to explain what (I believe) the issue is. Syntactically, field names are either:
- an identifier (unquoted string), 
- a string 
- or a computed field name (```{[e]: ... }```)

The problem comes at parsing, where we are erasing this distinction:

```hs
data EField a = EField
  { key :: a,
    value :: a,
    computed :: Bool,
    visibility :: Visibility,
    override :: Bool
  }
```
But this distinction would be needed in the pretty printer. A possible solution would be to change the field key to e.g.:
```hs
data FieldName a = Computed a | String String | Ident String
```
On the desugaring phase we can reify them all to expressions.

**Comment by moleike** [comment]
@ozkutuk would you like to work on this one? I'd like to get this fixed so that the pretty-printer can be re-enabled 😊

**Comment by ozkutuk** [comment]
Sure, I actually have been looking into it :smile: I think I need to spend some time reading through parsing and desugaring phases to truly understand what the problem really is.

**Comment by ozkutuk** [comment]
One thing that caught my attention is that the dot-lookup expression is defined as `ELookup a a`, rather than `ELookup a Ident`, which the spec suggests. Is there a particular reason to do so? This seems to be one of the reasons that blocks us from getting rid of unquoted strings altogether and use identifiers instead (which is more inline with what the spec suggests).

**Comment by moleike** [comment]
I can't recall why did I choose to do that 🤔 But now that I revisit the code seems to me that replacing the rhs of `ELookup` with an identifier is a good idea. Bear in mind though, that the core AST only has primitive operation (lookup) for both indexing and lookup.
