### ISSUE TITLE
Is it possible to support ghc-9.2?

### ISSUE THREAD

**Issue by skiars** [moleike/haskell-jsonnet#56]
I compiled with ghc-9.2.2 and found some errors, is there any plan to fix it?

**Comment by moleike** [comment]
Yes, I haven't added GHC 9 support yet, but it's on my to-do list.

**Comment by Skiars** [comment]
I tried some adaptations to GHC 9.2.2 and it worked, but I'm not sure if it's appropriate.

Here is my commit: https://github.com/Skiars/haskell-jsonnet/commit/3c47adc24d959b6d589c0c5e59f4e8d526a3f60e

**Comment by moleike** [comment]
It is very appropriate, thanks. I see the main breaking change was in aeson (`KeyMap` part).
Just one thing: would you mind running `cabal gen-bounds` after a build, and paste the output into the project's Cabal file. Maybe you need to remove all bounds first.
